# hugo.toml

baseURL = "https://themahani.github.io/" 
languageCode = "en-us"
title = "Ali Mahani -- Personal Website"
theme = "congo"

# Main menu navigation
[menu]
  [[menu.main]]
    name = "Posts"
    pageRef = "posts"
    weight = 10
  [[menu.main]]
    name = "About"
    pageRef = "about"
    weight = 20
  [[menu.main]]
    name = "Tags"
    pageRef = "tags"
    weight = 30
