# .github/workflows/deploy.yml

name: Build and Deploy Hugo Site to gh-pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the 'main' branch
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # Fetch Hugo themes
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      # Step 2: Set up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true # Congo theme requires the extended version

      # Step 3: Build the site
      - name: Build
        run: hugo --minify

      # Step 4: Deploy the 'public' directory to the 'gh-pages' branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          # The GITHUB_TOKEN is automatically provided by GitHub
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The branch to deploy to
          publish_branch: gh-pages
          # The directory that contains the built site
          publish_dir: ./public
